//! The optional OpenSCAD derivative.
//!
//! OpenSCAD is **not** the geometry kernel. `generated.scad` is a hackable
//! approximation of the canonical B-rep, regenerated on every rebuild;
//! `custom.scad` is written once and never touched again. Changes made in
//! `custom.scad` do not feed back into the STEP model.

use crate::cad::ensure_dir;
use crate::error::{ExportError, Result};
use crate::paths::ExportPaths;
use kicase_geometry::profile::{Loop2, Profile2d};
use kicase_geometry::units::Length;
use kicase_model::model::{CutPlacement, Enclosure};
use std::fmt::Write as _;
use std::path::PathBuf;

/// Arc segments used when flattening curves for OpenSCAD.
const ARC_SEGMENTS: usize = 48;

/// Writes `generated.scad`, and `custom.scad` if it does not already exist.
pub fn export_openscad(enclosure: &Enclosure, paths: &ExportPaths) -> Result<Vec<PathBuf>> {
    ensure_dir(&paths.openscad_dir)?;

    let generated = paths.generated_scad();
    std::fs::write(&generated, generated_scad(enclosure))
        .map_err(|source| ExportError::io(generated.display(), source))?;

    let mut written = vec![generated];

    let custom = paths.custom_scad();
    if !custom.exists() {
        std::fs::write(&custom, CUSTOM_SCAD_TEMPLATE)
            .map_err(|source| ExportError::io(custom.display(), source))?;
        written.push(custom);
    }
    Ok(written)
}

const CUSTOM_SCAD_TEMPLATE: &str = "\
include <generated.scad>

// This file is never overwritten by KiCase.
//
// Edit it freely: add print-specific tweaks, extra holes, text, whatever the
// canonical model does not cover. Note that changes here do NOT feed back into
// the STEP model that KiCad shows; they only affect what this file renders.

enclosure();
";

fn generated_scad(enclosure: &Enclosure) -> String {
    let layout = enclosure.layout;
    let shell = &enclosure.shell;
    let mut out = String::new();

    let _ = writeln!(
        out,
        "// Generated by KiCase. Do not edit: this file is overwritten on every rebuild.\n\
         // It is an approximation of the canonical STEP model, provided so the design\n\
         // can be hacked in OpenSCAD. Curves are flattened to {ARC_SEGMENTS} segments per arc.\n"
    );

    let _ = writeln!(out, "// Parameters");
    let _ = writeln!(out, "wall = {};", fmt(shell.wall));
    let _ = writeln!(out, "floor_thickness = {};", fmt(shell.floor));
    let _ = writeln!(out, "lid_thickness = {};", fmt(enclosure.lid.thickness));
    let _ = writeln!(out, "lid_fit_clearance = {};", fmt(enclosure.lid.fit_clearance));
    let _ = writeln!(out, "lid_lip_depth = {};", fmt(enclosure.lid.lip_depth));
    let _ = writeln!(out, "lid_lip_thickness = {};", fmt(enclosure.lid.lip_thickness));
    let _ = writeln!(out, "case_bottom_z = {};", fmt(layout.case_bottom));
    let _ = writeln!(out, "cavity_floor_z = {};", fmt(layout.cavity_floor));
    let _ = writeln!(out, "rim_z = {};", fmt(layout.rim));
    let _ = writeln!(out, "shell_height = {};", fmt(layout.shell_height()));
    let _ = writeln!(out, "cavity_height = {};\n", fmt(layout.cavity_height()));

    let _ = writeln!(out, "// The wall centre line, in board XY (millimetres).");
    let _ = writeln!(out, "// Arcs are sampled: OpenSCAD has no arc, only many-sided circles.");
    let _ = writeln!(out, "wall_centreline = {};\n", polygon_literal(&shell.cavity_profile));

    // When every segment was drawn at the same width — the usual case — say so
    // with an offset. It stays readable and parametric: change `wall` and the
    // model follows. Only a wall of mixed widths needs spelling out segment by
    // segment, because no single offset can describe it.
    let curves = shell.cavity_profile.outer.curves();
    let uniform =
        shell.wall_widths.iter().all(|w| w.approx_eq(shell.wall, kicase_geometry::types::TOL));

    if uniform {
        let _ = writeln!(
            out,
            "// Every segment is drawn at the same width, so the wall is just an offset.\n\
             module exterior_profile() {{\n    \
                 offset(r = wall / 2) polygon(points = wall_centreline);\n\
             }}\n\n\
             module cavity_profile() {{\n    \
                 offset(r = -wall / 2) polygon(points = wall_centreline);\n\
             }}\n"
        );
    } else {
        let _ = writeln!(
            out,
            "// The wall is drawn at differing widths, so it is the union of what\n\
             // each segment covers rather than a single offset."
        );
        let _ = writeln!(out, "module wall_footprint() {{");
        let _ = writeln!(out, "    union() {{");
        for (index, curve) in curves.iter().enumerate() {
            let width = shell.wall_widths.get(index).copied().unwrap_or(shell.wall);
            if let Some(stroke) = curve.stroke_loop(width) {
                let _ = writeln!(out, "        polygon(points = {});", loop_literal(&stroke));
            }
            let next = &curves[(index + 1) % curves.len()];
            let next_width =
                shell.wall_widths.get((index + 1) % curves.len()).copied().unwrap_or(shell.wall);
            let radius = width.min(next_width) / 2.0;
            if radius.is_positive() {
                let _ = writeln!(
                    out,
                    "        translate([{}, {}]) circle(r = {}, $fn = 32);",
                    fmt(curve.end().x),
                    fmt(curve.end().y),
                    fmt(radius)
                );
            }
            if let Some(join) = kicase_geometry::profile::miter_join(curve, next, width, next_width)
            {
                let _ = writeln!(out, "        polygon(points = {});", loop_literal(&join));
            }
        }
        let _ = writeln!(out, "    }}\n}}\n");
        let _ = writeln!(
            out,
            "module exterior_profile() {{\n    \
                 union() {{\n        \
                     polygon(points = wall_centreline);\n        \
                     wall_footprint();\n    \
                 }}\n\
             }}\n\n\
             module cavity_profile() {{\n    \
                 difference() {{\n        \
                     polygon(points = wall_centreline);\n        \
                     wall_footprint();\n    \
                 }}\n\
             }}\n"
        );
    }

    // The cavity is hollowed out before anything is added to it, exactly as the
    // builder does it. Cut the other way round and every interior wall and
    // every boss standing on the floor would be swept away again.
    let _ = writeln!(
        out,
        "module enclosure_bottom() {{\n    \
             difference() {{\n        \
                 union() {{\n            \
                     difference() {{\n                \
                         translate([0, 0, case_bottom_z])\n                    \
                             linear_extrude(height = shell_height)\n                        \
                                 exterior_profile();\n                \
                         translate([0, 0, cavity_floor_z])\n                    \
                             linear_extrude(height = cavity_height + 1)\n                        \
                                 cavity_profile();\n            \
                     }}\n            \
                     interior_walls();\n            \
                     added_solids();\n        \
                 }}\n        \
                 cutouts();\n    \
             }}\n\
         }}\n"
    );

    let _ = writeln!(
        out,
        "module enclosure_lid() {{\n    \
             difference() {{\n        \
                 union() {{\n            \
                     translate([0, 0, rim_z])\n                \
                         linear_extrude(height = lid_thickness)\n                    \
                             exterior_profile();\n            \
                     translate([0, 0, rim_z - lid_lip_depth])\n                \
                         linear_extrude(height = lid_lip_depth)\n                    \
                             difference() {{\n                        \
                                 offset(r = -lid_fit_clearance) cavity_profile();\n                        \
                                 offset(r = -lid_fit_clearance - lid_lip_thickness) cavity_profile();\n                    \
                             }}\n        \
                 }}\n        \
                 cutouts();\n    \
             }}\n\
         }}\n"
    );

    // Interior walls. Unlike the outer wall these are written out already
    // offset rather than as an `offset(r = wall / 2)`, because an island is not
    // tied to the wall parameter and may be drawn at a width of its own.
    let _ = writeln!(out, "module interior_walls() {{");
    if shell.islands.is_empty() {
        let _ = writeln!(out, "    // nothing drawn inside the outline");
    }
    for island in &shell.islands {
        let half: Vec<Length> = (0..island.outline.curves().len())
            .map(|index| island.widths.get(index).copied().unwrap_or(shell.wall) / 2.0)
            .collect();
        let inward: Vec<Length> = half.iter().map(|h| -*h).collect();
        let Some(outer) = island.outline.offset_each(&half) else { continue };
        let smallest = half.iter().copied().reduce(Length::min).unwrap_or(Length::ZERO);
        let inner = island
            .outline
            .offset_each(&inward)
            .filter(|inner| inner.stands_off(&island.outline, smallest));
        let _ = writeln!(
            out,
            "    translate([0, 0, cavity_floor_z]) linear_extrude(height = cavity_height)"
        );
        match inner {
            Some(inner) => {
                let _ = writeln!(out, "        difference() {{");
                let _ = writeln!(out, "            polygon(points = {});", loop_literal(&outer));
                let _ = writeln!(out, "            polygon(points = {});", loop_literal(&inner));
                let _ = writeln!(out, "        }}");
            },
            // Drawn narrower than its own stroke: a solid post, not a ring.
            None => {
                let _ = writeln!(out, "        polygon(points = {});", loop_literal(&outer));
            },
        }
    }
    let _ = writeln!(out, "}}\n");

    // Added solids.
    let _ = writeln!(out, "module added_solids() {{");
    if enclosure.solids.is_empty() {
        let _ = writeln!(out, "    // nothing on the Enclosure.Solids layer");
    }
    for solid in &enclosure.solids {
        let _ = writeln!(
            out,
            "    translate([0, 0, {}]) linear_extrude(height = {}) polygon(points = {}); // {}",
            fmt(solid.z_start),
            fmt(solid.height),
            polygon_literal(&solid.profile),
            solid.id
        );
    }
    let _ = writeln!(out, "}}\n");

    // Cutouts.
    let _ = writeln!(out, "module cutouts() {{");
    if enclosure.cutouts.is_empty() {
        let _ = writeln!(out, "    // nothing on the Enclosure.Cuts layer");
    }
    for cutout in &enclosure.cutouts {
        match &cutout.placement {
            CutPlacement::Vertical { .. } => {
                let _ = writeln!(
                    out,
                    "    translate([0, 0, {}]) linear_extrude(height = {}) \
                     offset(r = {}) polygon(points = {}); // {}",
                    fmt(layout.case_bottom - Length::from_mm(1.0)),
                    fmt(layout.total_height() + Length::from_mm(2.0)),
                    fmt(cutout.clearance),
                    polygon_literal(&cutout.profile),
                    cutout.id
                );
            },
            CutPlacement::Side { plane, .. } => {
                // Rebuild the datum frame in OpenSCAD with an explicit matrix,
                // which keeps this readable and avoids re-deriving angles.
                let m = [
                    [plane.u.x.mm(), plane.v.x.mm(), plane.normal().x.mm(), plane.origin.x.mm()],
                    [plane.u.y.mm(), plane.v.y.mm(), plane.normal().y.mm(), plane.origin.y.mm()],
                    [plane.u.z.mm(), plane.v.z.mm(), plane.normal().z.mm(), plane.origin.z.mm()],
                ];
                let _ = writeln!(
                    out,
                    "    multmatrix([[{:.6}, {:.6}, {:.6}, {:.6}], \
                     [{:.6}, {:.6}, {:.6}, {:.6}], [{:.6}, {:.6}, {:.6}, {:.6}], \
                     [0, 0, 0, 1]])",
                    m[0][0],
                    m[0][1],
                    m[0][2],
                    m[0][3],
                    m[1][0],
                    m[1][1],
                    m[1][2],
                    m[1][3],
                    m[2][0],
                    m[2][1],
                    m[2][2],
                    m[2][3],
                );
                let _ = writeln!(
                    out,
                    "        translate([0, 0, -100]) linear_extrude(height = 200) \
                     offset(r = {}) polygon(points = {}); // {}",
                    fmt(cutout.clearance),
                    polygon_literal(&cutout.profile),
                    cutout.id
                );
            },
        }
    }
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(
        out,
        "module enclosure() {{\n    \
             enclosure_bottom();\n    \
             enclosure_lid();\n\
         }}\n"
    );
    let _ = writeln!(out, "enclosure();");

    out
}

fn polygon_literal(profile: &Profile2d) -> String {
    // OpenSCAD's polygon() takes a single point list; holes would need paths,
    // and the outline is what matters for a hackable derivative.
    loop_literal(&profile.outer)
}

fn loop_literal(loop2: &Loop2) -> String {
    let polygon = loop2.to_polygon(ARC_SEGMENTS);
    let points: Vec<String> =
        polygon.points.iter().map(|p| format!("[{:.4}, {:.4}]", p.x.mm(), p.y.mm())).collect();
    format!("[{}]", points.join(", "))
}

fn fmt(value: Length) -> String {
    format!("{:.4}", value.mm())
}
