//! The KiCad 3D preview footprint.
//!
//! KiCad shows external 3D models by attaching them to footprints, so the
//! generated `enclosure.step` is hung on a single dedicated footprint that
//! carries no pads, is locked, and is excluded from the BOM and position files.

use crate::cad::ensure_dir;
use crate::error::{ExportError, Result};
use crate::paths::ExportPaths;
use kicase_geometry::units::Length;
use kicase_model::model::Enclosure;
use std::path::PathBuf;

/// Reference designator used to find the preview footprint again.
///
/// This is an *identity*, not a parameter: nothing about the enclosure is
/// encoded in it.
pub const PREVIEW_REFERENCE: &str = "ENCLOSURE_PREVIEW";

/// Value field text, purely informational.
pub const PREVIEW_VALUE: &str = "KiCase enclosure preview";

/// Builds the s-expression for the preview footprint.
///
/// Each path becomes its own `(model ...)` entry. KiCad shows and hides a
/// footprint's models individually (footprint properties, 3D Models tab), so
/// attaching the bottom and the lid separately is what lets either be hidden to
/// look inside the case.
///
/// The footprint sits at the board origin, because KiCase geometry is expressed
/// in board coordinates. KiCad's 3D scene puts a front-layer footprint's model
/// origin on the *top* surface of the board, while enclosure Z zero is the
/// *bottom* surface, so the model is offset down by the PCB thickness.
pub fn preview_footprint_sexpr(model_paths: &[&str], pcb_thickness: Length) -> String {
    let z_offset = -pcb_thickness.mm();
    let models: String = model_paths
        .iter()
        .map(|path| {
            format!(
                "\n  (model \"{path}\"\n    (offset (xyz 0 0 {z_offset:.4}))\n    \
                 (scale (xyz 1 1 1))\n    (rotate (xyz 0 0 0))\n  )"
            )
        })
        .collect();

    format!(
        r#"(footprint "{reference}"
  (version 20241229)
  (generator "kicase")
  (generator_version "10.0")
  (layer "F.Cu")
  (at 0 0)
  (locked yes)
  (descr "Generated by KiCase. Holds the enclosure 3D preview; safe to hide, do not edit.")
  (attr exclude_from_pos_files exclude_from_bom allow_missing_courtyard)
  (property "Reference" "{reference}"
    (at 0 0 0)
    (layer "F.SilkS")
    (hide yes)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (property "Value" "{value}"
    (at 0 0 0)
    (layer "F.Fab")
    (hide yes)
    (effects (font (size 1 1) (thickness 0.15)))
  ){models}
)"#,
        reference = PREVIEW_REFERENCE,
        value = PREVIEW_VALUE,
        models = models,
    )
}

/// Convenience wrapper that reads the PCB thickness from the model.
pub fn preview_footprint_for(enclosure: &Enclosure, model_paths: &[&str]) -> String {
    preview_footprint_sexpr(model_paths, enclosure.layout.pcb_top)
}

/// Name of the project-local footprint library KiCase writes.
pub const PREVIEW_LIBRARY: &str = "KiCase";

/// Writes the preview footprint into a project-local footprint library and
/// registers that library with the project.
///
/// This exists because KiCad 10.0.3's `ParseAndCreateItemsFromString` command
/// accepts a request and then creates nothing — verified against a running
/// KiCad, including with KiCad's own serialisation of an existing footprint as
/// the input. Until that command works, the preview footprint cannot be created
/// over IPC, so KiCase prepares everything and the user places it once with the
/// ordinary Add Footprint tool.
///
/// Returns the files that were written.
pub fn write_preview_library(paths: &ExportPaths, footprint: &str) -> Result<Vec<PathBuf>> {
    let library = paths.preview_library_dir();
    ensure_dir(&library)?;

    let mut written = Vec::new();
    let module = library.join(format!("{PREVIEW_REFERENCE}.kicad_mod"));
    std::fs::write(&module, footprint)
        .map_err(|source| ExportError::io(module.display(), source))?;
    written.push(module);

    if let Some(table) = register_library(&paths.project_dir)? {
        written.push(table);
    }
    Ok(written)
}

/// Adds a `KiCase` entry to the project's `fp-lib-table`, leaving any existing
/// entries untouched. Returns the path if the file was changed.
fn register_library(project_dir: &std::path::Path) -> Result<Option<PathBuf>> {
    let table = project_dir.join("fp-lib-table");
    let entry = format!(
        "  (lib (name \"{PREVIEW_LIBRARY}\")(type \"KiCad\")(uri \"${{KIPRJMOD}}/.enclosure/kicase.pretty\")(options \"\")(descr \"KiCase enclosure preview\"))\n"
    );

    let existing = std::fs::read_to_string(&table).unwrap_or_default();
    if existing.contains(&format!("(name \"{PREVIEW_LIBRARY}\")")) {
        return Ok(None);
    }

    let updated = if existing.trim().is_empty() {
        format!("(fp_lib_table\n  (version 7)\n{entry})\n")
    } else {
        // Insert before the final closing parenthesis of the existing table.
        match existing.rfind(')') {
            Some(index) => format!("{}{entry}{}", &existing[..index], &existing[index..]),
            None => return Ok(None),
        }
    };

    std::fs::write(&table, updated).map_err(|source| ExportError::io(table.display(), source))?;
    Ok(Some(table))
}

#[cfg(test)]
mod tests {
    use super::*;
    use kicase_geometry::units::mm;

    #[test]
    fn footprint_has_no_pads_and_is_excluded_from_fabrication_outputs() {
        let text = preview_footprint_sexpr(&ExportPaths::preview_model_references(), mm(1.6));
        assert!(!text.contains("(pad "), "the preview footprint must have no pads");
        assert!(text.contains("exclude_from_bom"));
        assert!(text.contains("exclude_from_pos_files"));
        assert!(text.contains("(locked yes)"));
        assert!(text.contains(PREVIEW_REFERENCE));
        assert!(text.contains("preview-bottom.step"));
        assert!(text.contains("preview-lid.step"));
        assert_eq!(text.matches("(model ").count(), 2);
    }

    #[test]
    fn bottom_and_lid_are_separate_models_so_either_can_be_hidden() {
        let text = preview_footprint_sexpr(&ExportPaths::preview_model_references(), mm(1.6));
        // KiCad shows and hides a footprint's 3D models one at a time, so the
        // two parts must be attached separately rather than as one assembly.
        assert_eq!(text.matches("(model ").count(), 2);
        assert!(text.contains("preview-bottom.step"));
        assert!(text.contains("preview-lid.step"));
        // Both start visible; hiding is the user's choice, per board.
        assert!(!text.contains("(hide yes)\n    (offset"));
    }

    #[test]
    fn registers_the_library_without_disturbing_existing_entries() {
        let dir = std::env::temp_dir().join(format!("kicase-fplib-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        let table = dir.join("fp-lib-table");
        std::fs::write(
            &table,
            "(fp_lib_table\n  (version 7)\n  (lib (name \"Mine\")(type \"KiCad\")(uri \"x\")(options \"\")(descr \"\"))\n)\n",
        )
        .expect("seed table");

        let paths = ExportPaths::new(&dir);
        write_preview_library(&paths, "(footprint \"x\")").expect("writes");

        let updated = std::fs::read_to_string(&table).expect("read back");
        assert!(updated.contains("(name \"Mine\")"), "existing entry was lost:\n{updated}");
        assert!(updated.contains("(name \"KiCase\")"), "KiCase entry missing:\n{updated}");
        assert!(dir.join(".enclosure/kicase.pretty/ENCLOSURE_PREVIEW.kicad_mod").exists());

        // Running twice must not add a second entry.
        write_preview_library(&paths, "(footprint \"x\")").expect("writes again");
        let twice = std::fs::read_to_string(&table).expect("read back");
        assert_eq!(twice.matches("(name \"KiCase\")").count(), 1);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn model_is_dropped_by_the_pcb_thickness() {
        let text = preview_footprint_sexpr(&["model.step"], mm(1.6));
        assert!(text.contains("(xyz 0 0 -1.6000)"), "offset missing in:\n{text}");
    }
}
